language: node_js
node_js: node
services: 
  - postgresql
before_install:
  - psql -c 'CREATE DATABASE instagramtest;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD '';" -U postgres
  - psql -c 'ALTER USER root WITH SUPERUSER;' -U postgres
install: 
  - npm install
script:
  - npm test